# Generated by Django 4.1.4 on 2022-12-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='contact',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
