# Generated by Django 4.1.4 on 2022-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_data_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='message',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
