# Generated by Django 4.1.6 on 2023-02-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_data_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='invited_people_num',
            field=models.IntegerField(null=True),
        ),
    ]
